// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package po

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFc263e4eDecodeGithubComHaleyLeoZhangEmailServerModelPo(in *jlexer.Lexer, out *Email) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "title":
			out.Title = string(in.String())
		case "content":
			out.Content = string(in.String())
		case "sender_name":
			out.SenderName = string(in.String())
		case "receiver":
			out.Receiver = string(in.String())
		case "receiver_name":
			out.ReceiverName = string(in.String())
		case "attachment":
			out.Attachment = string(in.String())
		case "remark":
			out.Remark = string(in.String())
		case "is_ok":
			out.IsOk = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFc263e4eEncodeGithubComHaleyLeoZhangEmailServerModelPo(out *jwriter.Writer, in Email) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"sender_name\":"
		out.RawString(prefix)
		out.String(string(in.SenderName))
	}
	{
		const prefix string = ",\"receiver\":"
		out.RawString(prefix)
		out.String(string(in.Receiver))
	}
	{
		const prefix string = ",\"receiver_name\":"
		out.RawString(prefix)
		out.String(string(in.ReceiverName))
	}
	{
		const prefix string = ",\"attachment\":"
		out.RawString(prefix)
		out.String(string(in.Attachment))
	}
	{
		const prefix string = ",\"remark\":"
		out.RawString(prefix)
		out.String(string(in.Remark))
	}
	{
		const prefix string = ",\"is_ok\":"
		out.RawString(prefix)
		out.Int(int(in.IsOk))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Email) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFc263e4eEncodeGithubComHaleyLeoZhangEmailServerModelPo(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Email) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFc263e4eEncodeGithubComHaleyLeoZhangEmailServerModelPo(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Email) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFc263e4eDecodeGithubComHaleyLeoZhangEmailServerModelPo(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Email) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFc263e4eDecodeGithubComHaleyLeoZhangEmailServerModelPo(l, v)
}
