// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package vo

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB3bcdb0DecodeGithubComHaleyLeoZhangEmailServerModelVo(in *jlexer.Lexer, out *SendEmailRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Title":
			out.Title = string(in.String())
		case "Content":
			out.Content = string(in.String())
		case "Receiver":
			out.Receiver = string(in.String())
		case "ReceiverName":
			out.ReceiverName = string(in.String())
		case "SenderName":
			out.SenderName = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB3bcdb0EncodeGithubComHaleyLeoZhangEmailServerModelVo(out *jwriter.Writer, in SendEmailRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"Content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"Receiver\":"
		out.RawString(prefix)
		out.String(string(in.Receiver))
	}
	{
		const prefix string = ",\"ReceiverName\":"
		out.RawString(prefix)
		out.String(string(in.ReceiverName))
	}
	{
		const prefix string = ",\"SenderName\":"
		out.RawString(prefix)
		out.String(string(in.SenderName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SendEmailRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB3bcdb0EncodeGithubComHaleyLeoZhangEmailServerModelVo(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SendEmailRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB3bcdb0EncodeGithubComHaleyLeoZhangEmailServerModelVo(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SendEmailRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB3bcdb0DecodeGithubComHaleyLeoZhangEmailServerModelVo(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SendEmailRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB3bcdb0DecodeGithubComHaleyLeoZhangEmailServerModelVo(l, v)
}
